Fix Lua 5.2 include directory
In Linux distributions Lua 5.2 is usually provided in a namespace
which includes the version number. This results in the following build
errors on Debian for instance:

-----
In file included from src/lua/luathread.h:24,
                 from src/scripteditwidget.h:22,
                 from src/mainwindow.h:39,
                 from src/qosmic.cpp:25:
src/lua/lunar.h:12:10: fatal error: lua.h: No such file or directory
 #include "lua.h"
          ^~~~~~~
compilation terminated.
make: *** [Makefile:1773: .obj/qosmic.o] Error 1
-----

This patch fixes such erros by using "lua5.2" instead of just "lua" for
the include path.

It seems that on Gentoo (#32) and Linux Mint (#31) the same issue is
present.